version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ./:/usr/src/app
    command: sh -c "cd workplace && yarn add react-router-dom firebase bootstrap reactstrap react-loading-overlay formik yup && yarn start"
    ports:
     - "3000:3000"
    tty: true